using System; //uses system [allows to use system]
using System.Collections.Generic; //uses the generic system collection [allows generic system collections]
using System.ComponentModel; //uses the system component model [allows for using component models]
using System.Data; //uses the system data [allows for using system memory]
using System.Drawing; //uses system drawing for UI [allows for making UIs]
using System.Linq; //uses system linq [allows the use of classes]
using System.Text; //uses system text [allows to be able to show text]
using System.Threading.Tasks; //uses system task threading [allow to thread tasks]
using System.Windows.Forms; //uses windows form [allows to use winform apps]

namespace Calculater //names the app
{
    public partial class Form1 : Form   //autogenerated
    {
        public Form1()
        {
            InitializeComponent();
        }

        private void label1_Click(object sender, EventArgs e)
        {

        }

        private void button12_MouseClick(object sender, MouseEventArgs e) //Does a action on mouseclick
        {
            string v = richTextBox2.Text; //Makes a String Variable [V] equals to the text of richTextBox2 {string saved a writtenValue as a name(usually used as a variable)}
            string v2 = "";               //Makes a String Variable [V2] equals to no text
            if (v == v2) //if Variable [V] (the text of richTextBox2) equals to Variable [V2] (no text)
            {   //then
                richTextBox1.Text = richTextBox1.Text + "0"; //writes 0 in richTextBox1
            }
            else //if Variable [V] (the text of richTextBox2) doesnt equal to Variable [V2] (no text) {Shortcut:: else}
            {    //then {included in shortcut:: else}
                richTextBox3.Text = richTextBox3.Text + "0"; //writes 0 in richTextBox3
            }
        }

        private void button1_MouseClick(object sender, MouseEventArgs e) //Does a action on mouseclick
        {
            string v = richTextBox2.Text; //Makes a Variable [V] equals to the text of richTextBox2
            string v2 = "";               //Makes a Variable [V2] equals to no text
            if (v == v2)                  //if Variable [V] (the text of richTextBox2) equals to Variable [V2] (no text)
            { //then
                richTextBox1.Text = richTextBox1.Text + "1"; //writes 2 in richTextBox1
            }
            else //else
            {
                richTextBox3.Text = richTextBox3.Text + "1"; //writes 2 in richTextBox3
            }
        }
 
        private void button2_MouseClick(object sender, MouseEventArgs e) //Does a action on mouseclick
        {
            string v = richTextBox2.Text; //Makes a Variable [V] equals to the text of richTextBox2
            string v2 = "";               //Makes a Variable [V2] equals to no text
            if (v == v2)                  //if Variable [V] (the text of richTextBox2) equals to Variable [V2] (no text)
            {
                richTextBox1.Text = richTextBox1.Text + "2"; //writes 2 in richTextBox1
            }
            else
            {
                richTextBox3.Text = richTextBox3.Text + "2"; //writes 2 in richTextBox3
            }
        }

        private void button3_MouseClick(object sender, MouseEventArgs e) //Does a action on mouseclick
        {
            string v = richTextBox2.Text; //Makes a Variable [V] equals to the text of richTextBox2
            string v2 = "";               //Makes a Variable [V2] equals to no text
            if (v == v2)                  //if Variable [V] (the text of richTextBox2) equals to Variable [V2] (no text)
            {
                richTextBox1.Text = richTextBox1.Text + "3"; //writes 3 in richTextBox1
            }
            else
            {
                richTextBox3.Text = richTextBox3.Text + "3"; //writes 3 in richTextBox1
            }
        }

        private void button6_MouseClick(object sender, MouseEventArgs e) //Repeats the above but with a different number
        {
            string v = richTextBox2.Text;
            string v2 = "";
            if (v == v2)
            {
                richTextBox1.Text = richTextBox1.Text + "4";
            }
            else
            {
                richTextBox3.Text = richTextBox3.Text + "4";
            }
        }

        private void button5_MouseClick(object sender, MouseEventArgs e) //Repeats the above but with a different number
        {
            string v = richTextBox2.Text;
            string v2 = "";
            if (v == v2)
            {
                richTextBox1.Text = richTextBox1.Text + "5";
            }
            else
            {
                richTextBox3.Text = richTextBox3.Text + "5";
            }
        }

        private void button4_MouseClick(object sender, MouseEventArgs e) //Repeats the above but with a different number
        {
            string v = richTextBox2.Text;
            string v2 = "";
            if (v == v2)
            {
                richTextBox1.Text = richTextBox1.Text + "6";
            }
            else
            {
                richTextBox3.Text = richTextBox3.Text + "6";
            }
        }

        private void button9_MouseClick(object sender, MouseEventArgs e) //Repeats the above but with a different number
        {
            string v = richTextBox2.Text;
            string v2 = "";
            if (v == v2)
            {
                richTextBox1.Text = richTextBox1.Text + "7";
            }
            else
            {
                richTextBox3.Text = richTextBox3.Text + "7";
            }
        }

        private void button8_MouseClick(object sender, MouseEventArgs e) //Repeats the above but with a different number
        {
            string v = richTextBox2.Text;
            string v2 = "";
            if (v == v2)
            {
                richTextBox1.Text = richTextBox1.Text + "8";
            }
            else
            {
                richTextBox3.Text = richTextBox3.Text + "8";
            }
        }

        private void button7_MouseClick(object sender, MouseEventArgs e) //Repeats the above but with a different number
        {
            string v = richTextBox2.Text;
            string v2 = "";
            if (v == v2)
            {
                richTextBox1.Text = richTextBox1.Text + "9";
            }
            else
            {
                richTextBox3.Text = richTextBox3.Text + "9";
            }
        }

        private void button10_MouseClick(object sender, MouseEventArgs e) //Does a action on mouseclick
        {
            richTextBox2.Text = "X"; //Writes Multiplication symbol (X) in richTextBox2
        }

        private void button11_MouseClick(object sender, MouseEventArgs e) //Does a action on mouseclick
        {
            if(richTextBox2.Text == "X") //if the text in richTextBox2 is equal to multiplication symbol (X)
            { //then
                string xy = richTextBox1.Text; //Takes the number in richTextBox1 as a variable [xy] 
                string yx = richTextBox3.Text; //Takes the number in richTextBox3 as a variable [yx] 
                int x = int.Parse(xy); //makes the string{writtenValue}named [xy] as a integer{numberValue}named [X] {Integer saves a numberValue as a name(usually used as a variable)}
                int y = int.Parse(yx); //makes the string{writtenValue}named [yx] as a integer{numberValue}named [Y]
                int v = x*y; //makes a integer variable{a variable which is a numberValue} which is the result of integer variable[X] multiplicated (X) by integer variable[Y]
                string answer = v.ToString(); //makes a string{writtenValue}named [answer] that is equal to the integer variable{numberValue}named [v]
                richTextBox4.Text = answer; //writes the answer in richTextBox4
            } //then
            if (richTextBox2.Text == "+") //if the text in richTextBox2 is equal to the addition symbol (+) <most same on top>
            { //then
                string xy = richTextBox1.Text;
                string yx = richTextBox3.Text;
                int x = int.Parse(xy);
                int y = int.Parse(yx);
                int v = x + y; //* is changed to + since this does addition not multiplication
                string answer = v.ToString();
                richTextBox4.Text = answer;
            } //then
            if (richTextBox2.Text == "-") //if the text in richTextBox2 is equal to the subtraction symbol (-) <most same on top>
            { //then
                string xy = richTextBox1.Text;
                string yx = richTextBox3.Text;
                int x = int.Parse(xy);
                int y = int.Parse(yx);
                int v = x - y; //+ is changed to - since this does subtraction not addition
                string answer = v.ToString();
                richTextBox4.Text = answer;
            } //then
            if (richTextBox2.Text == ":") //if the text in richTextBox2 is equal to the division symbol (:) 
            { //then
                string xy = richTextBox1.Text; //Takes the number in richTextBox1 as a variable [xy] 
                string yx = richTextBox3.Text; //Takes the number in richTextBox3 as a variable [yx] 
                int x = int.Parse(xy); //makes the string{writtenValue}named [xy] as a integer{numberValue}named [X] {A integer variable is a Variable that has a numberValue}
                int y = int.Parse(yx); //makes the string{writtenValue}named [yx] as a integer{numberValue}named [Y]
                int v = x / y; //makes a integer variable{a variable which is a numberValue} which is the result of integer variable[X] divided (/) by integer variable[Y]
                string answer = v.ToString(); //makes a string{writtenValue}named [answer] that is equal to the integer variable{numberValue}named [v]
                richTextBox4.Text = answer; //writes the answer in richTextBox4
                string ver1 = richTextBox1.Text; //creates a variable that equals to the text in richTextBox1
                string ver2 = richTextBox3.Text; //creates a variable that equals to the text in richTextBox3
                int v1 = int.Parse(ver1); //makes the string{writtenValue}named [ver1] as a integer{numberValue}named [v1]
                int v2 = int.Parse(ver2); //makes the string{writtenValue}named [ver2] as a integer{numberValue}named [v2]
                if (v1 < v2) //if the integerVariable{numberValue}named [v1] is smaller than integerVariable{numberValue}named [v2]
                { //then
                    richTextBox1.Text = richTextBox1.Text + "0"; //adds a 0 at the end of richTextBox1
                    string zb = richTextBox1.Text; //Takes the number in richTextBox1 as a variable [zb] 
                    string bz = richTextBox3.Text; //Takes the number in richTextBox3 as a variable [bz]
                    int z = int.Parse(zb); //makes the string{writtenValue}named [zb] as a integer{numberValue}named [z]
                    int b = int.Parse(bz); //makes the string{writtenValue}named [bz] as a integer{numberValue}named [b]
                    int r = (z / b); //makes a integer variable{a variable which is a numberValue} which is the result of integer variable[z] divided (/) by integer variable[b]
                    string result = r.ToString(); //makes a string{writtenValue}named [result] that is equal to the integer variable{numberValue}named [r]
                    richTextBox4.Text = "0." + result; //writes 0. in the begining of the answer in richTextBox4
                    richTextBox1.Text = ""; //clears richTextBox1
                    richTextBox2.Text = ""; //clears richTextBox2
                    richTextBox3.Text = ""; //clears richTextBox3
                }

            }



            if (richTextBox2.Text == "%") //if the text in richTextBox2 is equal to the percentage symbol (%) 
            {
                richTextBox1.Text = richTextBox1.Text + "0"; //adds a 0 at the end of richTextBox1
                string xy = richTextBox1.Text; //Takes the number in richTextBox1 as a variable [xy] 
                string yx = richTextBox3.Text; //Takes the number in richTextBox3 as a variable [yx] 
                int x = int.Parse(xy); //makes the string{writtenValue}named [xy] as a integer{numberValue}named [X] {A integer variable is a Variable that has a numberValue}
                int y = int.Parse(yx); //makes the string{writtenValue}named [yx] as a integer{numberValue}named [Y]
                int v = (x / y) * 10; //makes a integer variable{a variable which is a numberValue} which is the result of integer variable[X] divided (/) by integer variable[Y]
                string answer = v.ToString(); //makes a string{writtenValue}named [answer] that is equal to the integer variable{numberValue}named [v]
                richTextBox4.Text = answer + "%"; //write percentage at the end of the answer and puts that answer in richTextBox4
                richTextBox1.Text = ""; //clears richTextBox1
                richTextBox2.Text = ""; //clears richTextBox2
                richTextBox3.Text = ""; //clears richTextBox3
            }
        }

        private void button16_MouseClick(object sender, MouseEventArgs e) //Does a action on mouseclick
        {
            richTextBox2.Text = "+"; //writes the plus symbol (+) in richTextBox2
        }

        private void button15_MouseClick(object sender, MouseEventArgs e) //Does a action on mouseclick
        {
            richTextBox2.Text = "-"; //write the minus symbol (-) in richTextBox2
        }

        private void button14_MouseClick(object sender, MouseEventArgs e) //Does a action on mouseclick
        {
            richTextBox2.Text = ":"; //writes the divided symbol (:) in richTextBox2
        }

        private void button13_MouseClick(object sender, MouseEventArgs e) //Does a action on mouseclick
        {
            richTextBox1.Text = ""; //clears richTextBox1
            richTextBox2.Text = ""; //clears richTextBox2
            richTextBox3.Text = ""; //clears richTextBox3
            richTextBox4.Text = ""; //clears richTextBox4
        }

        private void button17_MouseClick(object sender, MouseEventArgs e) //Does a action on mouseclick
        { 

            richTextBox2.Text = "%"; //writes the percentage symbol (%) in richTextBox2
            
        }

        private void button18_MouseClick(object sender, MouseEventArgs e) //Does a action on mouseclick
        {
            string xy = richTextBox1.Text; //Takes the number in richTextBox1 as a variable [xy] 
            int x = int.Parse(xy); //makes the string{writtenValue}named [xy] as a integer{numberValue}named [X] {A integer variable is a Variable that has a numberValue}
            int v = x * x; //makes a integer variable{a variable which is a numberValue} which is the result of integer variable[X] multiplicated (X) by integer variable[X]
            string answer = v.ToString(); //makes a string{writtenValue}named [answer] that is equal to the integer variable{numberValue}named [v]
            richTextBox4.Text = answer; //writes the answer in richTextBox4
        }

        private void button19_MouseClick(object sender, MouseEventArgs e) //Does a action on mouseclick
        {
            string xy = richTextBox1.Text; //Takes the number in richTextBox1 as a variable [xy] 
            int x = int.Parse(xy); //makes the string{writtenValue}named [xy] as a integer{numberValue}named [X] {A integer variable is a Variable that has a numberValue}
            int v = x * x * x; //makes a integer variable{a variable which is a numberValue} which is the result of integer variable[X] multiplicated (X) by integer variable[X] multiplicated (X) by integer variable[X]
            string answer = v.ToString(); //makes a string{writtenValue}named [answer] that is equal to the integer variable{numberValue}named [v]
            richTextBox4.Text = answer; //writes the answer in richTextBox4
        }

        private void button20_MouseClick(object sender, MouseEventArgs e) //unused
        {
           

        }
    }
}
